// react/src/css/Css.tsx
import { FunctionComponent } from "react";
import "./css.css";

export const Css: FunctionComponent = () => {
  const pets = ["Fluffy", "Buddy", "Luna"];

  return (
    <>
      <div className="content">
        <div>{pets.length - 1} Pets</div>
        <div className="pet-content">
          {pets.map(
            (pet) =>
              !pet.startsWith("B") && (
                <div
                  key={pet}
                  style={{
                    // eslint-disable-next-line @typescript-eslint/no-explicit-any
                    ["--pet-color" as any]: `#${Math.floor(
                      Math.random() * 16777215
                    ).toString(16)}`,
                  }}
                >
                  {pet}
                </div>
              )
          )}
        </div>
      </div>
      <div className="disclaimer">
        No sane person would do this in react nowadays, use tailwind or cssInJs
      </div>
    </>
  );
};

// svelte/src/routes/css/+page.svelte
<script lang="ts">
	const pets = ['Fluffy', 'Buddy', 'Luna'];
</script>

<div class="content">
	<div>{pets.length - 1} Pets</div>
	<div class="pet-content">
		{#each pets as pet}
			{#if !pet.startsWith('B')}
				<div style="--pet-color: #{Math.floor(Math.random() * 16777215).toString(16)}">{pet}</div>
			{/if}
		{/each}
	</div>
</div>

<style>
	.content {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
	}
	.pet-content {
		display: flex;
	}
	.pet-content div {
		margin-right: 10px;
		color: var(--pet-color);
	}
</style>
