// react/src/globalState/globalState.tsx
import { Link } from "react-router-dom";
import { useCounter } from "./state";

export const GlobalState = () => {
  const { count, setCount } = useCounter();

  function handleClick() {
    setCount(count + 1);
  }

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "1rem",
      }}
    >
      <div>
        <button style={{ fontSize: "2rem" }} onClick={handleClick}>
          Clicked {count} {count === 1 ? "time" : "times"}
        </button>
      </div>
      <Link to="/globalState/viewer">View State</Link>
      <Link to="/">Back to Index</Link>
    </div>
  );
};

// svelte/src/routes/globalState/+page.svelte
<script lang="ts">
	import { counter } from '$lib/counter';

	function incrementCount() {
		counter.update((n) => n + 1);
	}

	let count = 0;

	counter.subscribe((n) => {
		count = n;
	});
</script>

<div style="display: flex; flex-direction: column;  align-items: center; gap: 1rem;">
	<button style="font-size: 2rem;" on:click={incrementCount}>
		Clicked {count}
		{count === 1 ? 'time' : 'times'}
	</button>
	<a href="/globalState/viewer">View State</a>
	<a href="/">Index</a>
</div>
