// react/src/reactivity/reactivity.tsx
import { useState } from "react";

export const Reactivity = () => {
  const [count, setCount] = useState(0);
  const [num1, setNum1] = useState(0);
  const [num2, setNum2] = useState(0);

  function handleClick() {
    setCount(count + 1);
  }

  const sum = num1 + num2; // Could do this here, better would be inside a useMemo

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "1rem",
      }}
    >
      <div>
        <button style={{ fontSize: "2rem" }} onClick={handleClick}>
          Clicked {count} {count === 1 ? "time" : "times"}
        </button>
      </div>
      <div>
        <label htmlFor="num1">Input 1:</label>
        <input
          type="number"
          id="num1"
          name="num1"
          value={num1}
          onChange={(event) => setNum1(Number.parseFloat(event.target.value))}
        />
      </div>
      <div>
        <label htmlFor="num2">Input 2:</label>
        <input
          type="number"
          id="num2"
          name="num2"
          value={num2}
          onChange={(event) => setNum2(Number.parseFloat(event.target.value))}
        />
      </div>
      <div>
        <p>
          {num1}+{num2}={sum}
        </p>
      </div>
    </div>
  );
};

// svelte/src/routes/reactivity/+page.svelte
<script>
	let count = 0;

	function handleClick() {
		count += 1;
	}

	let num1 = 0;
	let num2 = 0;
	let sum = 0;

	$: sum = num1 + num2;
</script>

<div style="display: flex; flex-direction: column;  align-items: center; gap: 1rem;">
	<button style="font-size: 2rem;" on:click={handleClick}>
		Clicked {count}
		{count === 1 ? 'time' : 'times'}
	</button>

	<div>
		<label for="num1">Num 1:</label>
		<input type="number" id="num1" name="num1" bind:value={num1} />
	</div>
	<div>
		<label for="num2">Num 2:</label>
		<input type="number" id="num2" name="num2" bind:value={num2} />
	</div>
	<div>
		<p>
			{num1}+{num2}={sum}
		</p>
	</div>
</div>
